# Generated by Django 5.0.7 on 2024-07-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='casuals', max_length=255),
            preserve_default=False,
        ),
    ]
