# Generated by Django 5.0.7 on 2024-07-15 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_remove_product_price_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
